describe('Parabank Registration',() => {
    it('Verify successful registration', () => {
        cy.visit('https://parabank.parasoft.com')
        cy.contains('Register').should('be.visible').and('contain', 'Register')

        //Register screen
        cy.contains('Register').click()
        cy.url().should('include', '/register.htm')
        cy.get('form > :nth-child(1) > b').should('be.visible').and('contain', 'Username')
        cy.get('form > :nth-child(2) > .input').should('be.visible').and('be.empty')
        cy.get('form > :nth-child(3)').should('be.visible').and('contain', 'Password')
        cy.get(':nth-child(4) > .input').should('be.visible').and('be.empty')

        //Enter values in the Registration form
        cy.get(':nth-child(1) > [align="right"] > b').should('be.visible').and('contain', 'First Name')
        cy.get("input[id='customer.firstName']").should('be.visible').and('be.empty').type('TestFirstName')
        cy.get(':nth-child(2) > [align="right"] > b').should('be.visible').and('contain', 'Last Name')
        cy.get("input[id='customer.lastName']").should('be.visible').and('be.empty').type('TestLastName')
        cy.get(':nth-child(3) > [align="right"] > b').should('be.visible').and('contain', 'Address')
        cy.get("input[id='customer.address.street']").should('be.visible').and('be.empty').type('TestAddress')
        cy.get(':nth-child(4) > [align="right"] > b').should('be.visible').and('contain', 'City')
        cy.get("input[id='customer.address.city']").should('be.visible').and('be.empty').type('TestCity')
        cy.get(':nth-child(5) > [align="right"] > b').should('be.visible').and('contain', 'State')
        cy.get("input[id='customer.address.state']").should('be.visible').and('be.empty').type('TestState')
        cy.get(':nth-child(6) > [align="right"] > b').should('be.visible').and('contain', 'Zip Code')
        cy.get("input[id='customer.address.zipCode']").should('be.visible').and('be.empty').type('12345')
        cy.get(':nth-child(7) > [align="right"]').should('be.visible').and('contain', 'Phone')
        cy.get("input[id='customer.phoneNumber']").should('be.visible').and('be.empty').type('1234567890')
        cy.get(':nth-child(8) > [align="right"]').should('be.visible').and('contain', 'SSN')
        cy.get("input[id='customer.ssn']").should('be.visible').and('be.empty').type('123-45-6789')
        cy.get(':nth-child(10) > [align="right"] > b').should('be.visible').and('contain', 'Username')
        var firstName = 'TestFirstNameB'
        cy.get("input[id='customer.username']").should('be.visible').and('be.empty').type(firstName)
        cy.get(':nth-child(11) > [align="right"] > b').should('be.visible').and('contain', 'Password')
        cy.get("input[id='customer.password']").should('be.visible').and('be.empty').type('TestPassword')
        cy.get(':nth-child(12) > [align="right"] > b').should('be.visible').and('contain', 'Confirm')  
        cy.get("#repeatedPassword").should('be.visible').and('be.empty').type('TestPassword')
        cy.get('[colspan="2"] > .button').should('be.visible').and('contain', 'Register').and('be.enabled')
        cy.get('[colspan="2"] > .button').click()
        cy.url().should('include', '/register.htm') 
        cy.get('.title').should('contain', `Welcome ${firstName}`)
        cy.get('#leftPanel > ul > :nth-child(8) > a').should('be.visible').and('contain', 'Log Out')
        cy.get('#leftPanel > ul > :nth-child(8) > a').click()   
          })          
    })